
package esp.dic2.archi.soapclient.proxy;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "SQLException", targetNamespace = "http://finalproject.softarchitecture.dic2.esp/")
public class SQLException_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SQLException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public SQLException_Exception(String message, SQLException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public SQLException_Exception(String message, SQLException faultInfo, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: esp.dic2.archi.soapclient.proxy.SQLException
     */
    public SQLException getFaultInfo() {
        return faultInfo;
    }

}
