
package esp.dic2.archi.soapclient.proxy;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "UserSoapService", targetNamespace = "http://finalproject.softarchitecture.dic2.esp/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserSoapService {


    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns java.lang.String
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authentification", targetNamespace = "http://finalproject.softarchitecture.dic2.esp/", className = "esp.dic2.archi.soapclient.proxy.Authentification")
    @ResponseWrapper(localName = "authentificationResponse", targetNamespace = "http://finalproject.softarchitecture.dic2.esp/", className = "esp.dic2.archi.soapclient.proxy.AuthentificationResponse")
    @Action(input = "http://finalproject.softarchitecture.dic2.esp/UserSoapService/authentificationRequest", output = "http://finalproject.softarchitecture.dic2.esp/UserSoapService/authentificationResponse", fault = {
        @FaultAction(className = SQLException_Exception.class, value = "http://finalproject.softarchitecture.dic2.esp/UserSoapService/authentification/Fault/SQLException")
    })
    public String authentification(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param motDePasse
     * @param nomUser
     * @param token
     * @return
     *     returns java.lang.String
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ajoutUtilisateur", targetNamespace = "http://finalproject.softarchitecture.dic2.esp/", className = "esp.dic2.archi.soapclient.proxy.AjoutUtilisateur")
    @ResponseWrapper(localName = "ajoutUtilisateurResponse", targetNamespace = "http://finalproject.softarchitecture.dic2.esp/", className = "esp.dic2.archi.soapclient.proxy.AjoutUtilisateurResponse")
    @Action(input = "http://finalproject.softarchitecture.dic2.esp/UserSoapService/ajoutUtilisateurRequest", output = "http://finalproject.softarchitecture.dic2.esp/UserSoapService/ajoutUtilisateurResponse", fault = {
        @FaultAction(className = SQLException_Exception.class, value = "http://finalproject.softarchitecture.dic2.esp/UserSoapService/ajoutUtilisateur/Fault/SQLException")
    })
    public String ajoutUtilisateur(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "nom_user", targetNamespace = "")
        String nomUser,
        @WebParam(name = "mot_de_passe", targetNamespace = "")
        String motDePasse)
        throws SQLException_Exception
    ;

}
